#!/bin/bash

version=$1
push=$2

if [ "" = "$version" ]
then
	version=latest
fi

cd ../..
docker build iota-node --tag iota-node:$version

if [ "--push" = "$push" ]
then
	read -p "Username:" username
	docker login --username=$username
	docker tag iota-node $username/iota-node:$version
	docker push $username/iota-node:$version
fi
